// This file is generated by Firebase Studio.
'use server';

/**
 * @fileOverview A personalized hint generation AI agent.
 *
 * - generatePersonalizedHint - A function that handles the hint generation process.
 * - GeneratePersonalizedHintInput - The input type for the generatePersonalizedHint function.
 * - GeneratePersonalizedHintOutput - The return type for the generatePersonalizedHint function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePersonalizedHintInputSchema = z.object({
  question: z.string().describe('The question the user is trying to answer.'),
  answerChoices: z.array(z.string()).describe('The possible answer choices for the question.'),
  userAnswer: z.string().optional().describe('The user selected answer, if any.'),
  topic: z.string().describe('The topic of the question.'),
});
export type GeneratePersonalizedHintInput = z.infer<typeof GeneratePersonalizedHintInputSchema>;

const GeneratePersonalizedHintOutputSchema = z.object({
  hint: z.string().describe('A personalized hint to help the user answer the question.'),
});
export type GeneratePersonalizedHintOutput = z.infer<typeof GeneratePersonalizedHintOutputSchema>;

export async function generatePersonalizedHint(input: GeneratePersonalizedHintInput): Promise<GeneratePersonalizedHintOutput> {
  return generatePersonalizedHintFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePersonalizedHintPrompt',
  input: {schema: GeneratePersonalizedHintInputSchema},
  output: {schema: GeneratePersonalizedHintOutputSchema},
  prompt: `You are an expert tutor, skilled at providing personalized hints to students who are struggling with a question.

  The student is currently trying to answer a question on the topic of {{topic}}.

  The question is:
  {{question}}

  The possible answers are:
  {{#each answerChoices}}
  - {{this}}
  {{/each}}

  The student has selected the following answer, if any:
  {{userAnswer}}

  Provide a personalized hint to help the student understand the underlying concepts and answer the question correctly.
  The hint should not directly give away the answer, but should guide the student towards the correct solution.
  The hint should be concise and easy to understand.
  `,
});

const generatePersonalizedHintFlow = ai.defineFlow(
  {
    name: 'generatePersonalizedHintFlow',
    inputSchema: GeneratePersonalizedHintInputSchema,
    outputSchema: GeneratePersonalizedHintOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
